// Generated by CoffeeScript 1.10.0
(function() {
  var threeSum,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  threeSum = function(nums) {
    var i, index, item1, item2, item3, itemUnq, j, k, key1, key2, key3, len, len1, len2, map, returns, target;
    if (nums.length < 3) {
      return [];
    }
    returns = [];
    map = [];
    for (key1 = i = 0, len = nums.length; i < len; key1 = ++i) {
      item1 = nums[key1];
      for (key2 = j = 0, len1 = nums.length; j < len1; key2 = ++j) {
        item2 = nums[key2];
        for (key3 = k = 0, len2 = nums.length; k < len2; key3 = ++k) {
          item3 = nums[key3];
          if (key1 !== key2 && key1 !== key3 && key2 !== key3) {
            if (item1 + item2 + item3 === 0) {
              target = [item1, item2, item3].sort(function(a, b) {
                return a - b;
              });
              itemUnq = target.join('');
              if (indexOf.call(map, itemUnq) < 0) {
                index = [key1, key2, key3].sort().join('');
                map.push(itemUnq);
                returns.push(target);
              }
            }
          }
        }
      }
    }
    returns = returns.sort(function(a, b) {
      if (a[0] !== b[0]) {
        return b[0] - a[0];
      }
      if (a[1] !== b[1]) {
        return b[1] - a[1];
      }
      if (a[2] !== b[2]) {
        return b[2] - a[2];
      }
    });
    return returns;
  };

}).call(this);
