// Generated by CoffeeScript 1.10.0
(function() {
  var getWeekBeginAndEnd, obj, var_dump;

  obj = {
    a: 'a',
    f: function() {
      return 'hello';
    }
  };

  getWeekBeginAndEnd = function() {
    var begin, date, day, dt, end;
    dt = begin = end = new Date();
    day = dt.getDay();
    date = dt.getDate();
    begin.setDate(date - day + 1);
    end.setDate(date + (5 - day + 1));
    console.log(begin);
    console.log(end);
    return [begin, end];
  };

  var_dump = function(obj) {
    var o;
    return ((function() {
      var i, len, results;
      results = [];
      for (i = 0, len = obj.length; i < len; i++) {
        o = obj[i];
        results.push(o);
      }
      return results;
    })()).join('');
  };

  getWeekBeginAndEnd();

}).call(this);
